version: '2'

services:
  f5_compare_db:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    environment:
     # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=f5_compare
      - MARIADB_DATABASE=f5_compare
  f5_compare_web:
    image: docker.io/bitnami/laravel:9
    ports:
      - '80:8000'
    environment:
      - DB_HOST=f5_compare_db
      - DB_PORT=3306
      - DB_USERNAME=f5_compare
      - DB_DATABASE=f5_compare
    volumes:
      - './compare:/app'
    depends_on:
      - f5_compare_db